#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

SensorType[in1] = sensorNone;
delay(1000);
SensorType[in1] = sensorGyro;
delay(1000);

clearTimer(T1);
while(time1(T1) < 10000){

motor[rightmotor] = 127;
motor[leftmotor] = 127;

	if (SensorValue[in1] > 20){
		motor[rightmotor] = 40;
	}

	else if (SensorValue[in1] == 0){
		motor[leftmotor] = 127;
		motor[rightmotor] = 127;
	}

	else if (SensorValue[in1] < 20){
		motor[leftmotor] = 40;
	}
	
	else{
		motor[rightmotor] = 0
		motor[leftmotor] = 0
	}

}
}
